"""drop templates table

Revision ID: 3b7e00d07c1f
Revises: aa9fef5e7bbb
Create Date: 2026-07-28 15:13:48.459723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b7e00d07c1f'
down_revision: Union[str, Sequence[str], None] = 'aa9fef5e7bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sender_pattern', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject_pattern', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('body_pattern', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('link_extract_regex', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], name=op.f('templates_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('templates_pkey'))
    )
    # ### end Alembic commands ###
